# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

name: Bug report
description: Report a problem
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A concise description of the bug.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: The release or commit used.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a list of steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Describe what you think should happen.
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: Actual behavior
      description: Describe what actually happens.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Any extra info you think may be relevant.
