# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/crawfxrd/yuffie/discussions
    about: Ask questions, general discussions
